# Generated by Django 2.2.16 on 2022-06-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
